#!/usr/bin/env bash

set -e

ROOT_DIR=tests/results/extraction
DIR=$ROOT_DIR/${2%.jazz}/$1
ECLIB=$(dirname $0)/../../eclib

if [ -d "${DIR}" ]; then rm -r ${DIR}; fi
mkdir -p $DIR

if [ "$1" = "arm" ]; then
	ARCH="--arch=arm-m4"
else
	ARCH="--arch=x86-64"
fi

set -x
set -o xtrace

MODES=(normal CT CTG val)

function ec_path { echo ${DIR}/jasmin_$1.ec; }

for MODE in "${MODES[@]}"; do
	$(dirname $0)/../jasmin2ec ${ARCH} -m ${MODE} -o $(ec_path $MODE) "$2"
done

for MODE in "${MODES[@]}"; do
	easycrypt -I Jasmin:${ECLIB} ${ECARGS} $(ec_path $MODE)
done
